(wip) 00-initial-config
andreslopezlu/sunnyside_page pull request #1
Opened 2022-07-06 03:46 UTC by andreslopezlu

2022-07-06 03:56 UTC, ImMPrada requested changes
Content to README

2022-07-06 03:56 UTC, ImMPrada commented on README.md
> +This is our first project, toto y yohan.
```suggestion
# sunnyside page

[description here]

## Authors
### Yohan
Linkedin:
Github:

### Toto:
LinkedIn:
Github: 

## Special thanks:
[frontendmentor](https://www.frontendmentor.io/challenges/sunnyside-agency-landing-page-7yVs3B6ef)
```

2022-07-06 04:00 UTC, ImMPrada requested changes
some thing we can put in README

2022-07-06 04:00 UTC, ImMPrada commented on README.md
> +[description here]
```suggestion
[description here]
[some screenshots here]
[live demo here]
```

2022-07-12 04:36 UTC, ImMPrada commented on styles/style.css
> +    --green2:#2C7566;
```suggestion
    --white: #FFFFFF;
    --black1: #24303E;
    --blue1: #052C3B;
    --blue2:#19536C;
    --gray1: #808397;
    --gray2: #A7AAAD;
    --gray3: #5B636D;
    --green1: #24554A;
    --green2: #2C7566;
```

2022-07-12 04:39 UTC, ImMPrada approved these changes
Yo creo que estaríamos listos para mergear, una vez veas mi comentario con sugerencia de cambio, y si estas de acuerdo lo ejectues, haces el merge

<img width="604" alt="image" src="https://user-images.githubusercontent.com/26731448/178409765-053fcde9-7a35-4933-8d67-0d19a08ee259.png">

2022-07-12 04:46 UTC, andreslopezlu commented
bro. se hace el merge de la rama 0-initial-config a main.

2022-07-12 04:47 UTC, merged